language: c

env:
  global:
    - TARGET_BOARD=odroid-xu3
    - TRAVIS_SECURE_ENV_VARS=true
    - ARCH=arm
    - CROSS_COMPILE=arm-linux-gnueabihf-

addons:
  apt:
    packages:

git:
  depth: 1

before_install:
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi

install:

before_script:
  - mkdir -p /opt/toolchains
  - wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xJf gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/toolchains
  - export PATH=/opt/toolchains/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin:$PATH

script:
  - make ${TARGET_BOARD}_defconfig
  - make

before_deploy:
  - export RELEASE_VERSION="${TARGET_BOARD}-${TRAVIS_BUILD_NUMBER}"
  - mkdir -p sd_fuse
  - wget -P sd_fuse/ https://github.com/hardkernel/u-boot/raw/odroidxu3-v2012.07/sd_fuse/hardkernel_1mb_uboot/bl1.bin.hardkernel
  - wget -P sd_fuse/ https://github.com/hardkernel/u-boot/raw/odroidxu3-v2012.07/sd_fuse/hardkernel_1mb_uboot/bl2.bin.hardkernel.1mb_uboot
  - wget -P sd_fuse/ https://github.com/hardkernel/u-boot/raw/odroidxu3-v2012.07/sd_fuse/hardkernel_1mb_uboot/sd_fusing.1M.sh
  - wget -P sd_fuse/ https://github.com/hardkernel/u-boot/raw/odroidxu3-v2012.07/sd_fuse/hardkernel_1mb_uboot/tzsw.bin.hardkernel
  - cp u-boot.bin sd_fuse/
  - mv sd_fuse/sd_fusing.1M.sh sd_fuse/sd_fusing.sh
  - tar czf u-boot-${RELEASE_VERSION}.tar.gz sd_fuse/
  - git config --global user.name ${GIT_USER_NAME}
  - git config --global user.email ${GIT_USER_EMAIL}
  - export REMOTE_URL=`git config --get remote.origin.url`
  - export GIT_TAG="travis/${RELEASE_VERSION}"
  - git tag ${GIT_TAG} -a -m "Tagged by Travis CI"
  - git push --quiet https://${PRIVATE_ACCESS_TOKEN}@${REMOTE_URL#$"https://"} ${GIT_TAG}

deploy:
  provider: releases
  api_key:
    secure: ${PRIVATE_ACCESS_TOKEN}
  file_glob: true
  file: u-boot-${RELEASE_VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
