language: c

env:
  global:
    - TRAVIS_SECURE_ENV_VARS=true

matrix:
  include:
    - env:
      - TARGET_BOARD=odroid-xu3
      - ARCH=arm
      - CROSS_COMPILE=arm-linux-gnueabihf-
    - env:
      - TARGET_BOARD=odroid-c2
      - ARCH=arm64
      - CROSS_COMPILE=aarch64-linux-gnu-

addons:
  apt:
    packages:

git:
  depth: 1

before_install:
        - if [ `uname -m` = x86_64 ]; then sudo apt-get install lzop build-essential gcc bc libncurses5-dev libc6-i386 lib32stdc++6 zlib1g:i386; fi

install:

before_script:
  - mkdir -p /opt/toolchains
  - wget https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02/arm-linux-gnueabihf/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar Jxf gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz -C /opt/toolchains/
  - export PATH=/opt/toolchains/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf/bin/:$PATH
  - wget https://releases.linaro.org/components/toolchain/binaries/7.4-2019.02/aarch64-linux-gnu/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
  - tar Jxf gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz -C /opt/toolchains/
  - export PATH=/opt/toolchains/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/:$PATH

script:
  - make ${TARGET_BOARD}_defconfig
  - make

before_deploy:
  - export BOARD=$(echo ${TARGET_BOARD} | tr -d '-')
  - export RELEASE_VERSION="${BOARD}-${TRAVIS_BUILD_NUMBER}"
  - tar czf u-boot-${RELEASE_VERSION}.tar.gz sd_fuse/*
  - git config --global user.name ${GIT_USER_NAME}
  - git config --global user.email ${GIT_USER_EMAIL}
  - export REMOTE_URL=`git config --get remote.origin.url`
  - export GIT_TAG="travis/${RELEASE_VERSION}"
  - git tag ${GIT_TAG} -a -m "Tagged by Travis CI"
  - git push --quiet https://${PRIVATE_ACCESS_TOKEN}@${REMOTE_URL#$"https://"} ${GIT_TAG}

deploy:
  provider: releases
  api_key: ${PRIVATE_ACCESS_TOKEN}
  file_glob: true
  file: u-boot-${RELEASE_VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

