language: c

env:
  global:
  - TARGET_BOARD=odroid-c2
  - TRAVIS_SECURE_ENV_VARS=true
  - ARCH=arm64
  - CROSS_COMPILE=aarch64-linux-gnu-
  - DEB_PACKAGES="kernel-image kernel-headers"

addons:
  apt:
    packages:
    - gcc-aarch64-linux-gnu
    - fakeroot
    - po-debconf
    - xmlto

git:
  depth: 3

before_install:

install:

script:
- make ${TARGET_BOARD}_defconfig
- make

before_deploy:
- export RELEASE_PACKAGES=$(ls ../*.deb)
- git config --global user.email "tobetter@gmail.com"
- git config --global user.name "Dongjin Kim"
- export GIT_TAG=travis/${TARGET_BOARD}-${TRAVIS_BUILD_NUMBER}
- git tag ${GIT_TAG} -a -m "Tagged by Travis (${TRAVIS_BUILD_NUMBER})"
- git push --quiet https://tobetter:${PRIVATE_ACCESS_TOKEN}@github.com/tobetter/u-boot ${GIT_TAG}

deploy:
  provider: releases
  api_key:
    secure: ${PRIVATE_ACCESS_TOKEN}
  file_glob: true
  file: ../*.deb
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
