#!/bin/sh
#
# Copyright (C) 2019 Dongjin Kim <tobetter@gmail.com>
#

set -x

[ -z ${binary_dir} ] && binary_dir="/usr/lib/u-boot/odroid-n2"

. ${binary_dir}/library.sh

case "$1" in
	install)
		echo "$1 install"
		;;
	configure)
		device=$(find_root_device)

		case ${device} in
			"/dev/mmcblk0"*)
				download_binary
				if [ -e ${device} ]; then
					flash_binary ${device} ${UBOOT_BINARY}
				fi
				;;
			*)
				;;
		esac
		;;
	*)
		exit 0
		;;
esac
